apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity-system

resources:
  - configmap-ldap.yaml
  - configmap-clients.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
