apiVersion: v1
kind: Service
metadata:
  name: freeradius-user-wifi
  namespace: identity-system
  labels:
    app.kubernetes.io/name: freeradius-user-wifi
    app.kubernetes.io/component: radius-auth
  annotations:
    metallb.universe.tf/address-pool: vlan600-management
    metallb.universe.tf/loadBalancerIPs: 192.168.255.60
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.255.60
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: freeradius-user-wifi
  ports:
  - name: radius-auth
    port: 1812
    targetPort: 1812
    protocol: UDP
  - name: radius-acct
    port: 1813
    targetPort: 1813
    protocol: UDP
  - name: radius-coa
    port: 3799
    targetPort: 3799
    protocol: UDP
