apiVersion: v1
kind: Service
metadata:
  name: chrony
  namespace: core-network
  labels:
    app.kubernetes.io/name: ntp
    app.kubernetes.io/component: chrony
  annotations:
    metallb.universe.tf/address-pool: vlan600-management
    metallb.universe.tf/loadBalancerIPs: 192.168.255.54
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.255.54
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ntp
    app.kubernetes.io/component: chrony
  ports:
  - name: ntp
    port: 123
    targetPort: 123
    protocol: UDP
