apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging-system

resources:
  - namespace.yaml
  - secret.yaml
  - statefulset-mongodb.yaml
  - statefulset-elasticsearch.yaml
  - deployment-graylog.yaml
  - service.yaml
