apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
  - namespace.yaml
  - secret.yaml
  - pvc-postgresql.yaml
  - statefulset-postgresql.yaml
  - deployment-zabbix-server.yaml
  - deployment-zabbix-web.yaml
  - daemonset-zabbix-agent.yaml
  - service.yaml
