apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - configmap-prometheus.yaml
  - configmap-alertmanager.yaml
  - configmap-alert-rules.yaml
  - configmap-snmp-exporter.yaml
  - configmap-grafana-datasources.yaml
  - configmap-grafana-dashboards.yaml
  - statefulset-prometheus.yaml
  - deployment-snmp-exporter.yaml
  - deployment-alertmanager.yaml
  - deployment-grafana.yaml
  - daemonset-node-exporter.yaml
  - pvc-grafana.yaml
  - service.yaml
