apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: core-network

resources:
  - namespace.yaml
  - configmap-named.yaml
  - configmap-zones.yaml
  - deployment.yaml
  - service.yaml
