apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: core-network
  labels:
    app.kubernetes.io/name: dns
    app.kubernetes.io/component: bind9
  annotations:
    metallb.universe.tf/address-pool: vlan600-management
    metallb.universe.tf/loadBalancerIPs: 192.168.255.53
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.255.53
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dns
    app.kubernetes.io/component: bind9
  ports:
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
