apiVersion: v1
kind: Service
metadata:
  name: freeradius-network
  namespace: core-auth
  labels:
    app.kubernetes.io/name: freeradius-network
    app.kubernetes.io/component: radius-auth
  annotations:
    metallb.universe.tf/address-pool: vlan600-management
    metallb.universe.tf/loadBalancerIPs: 192.168.255.50
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.255.50
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: freeradius-network
  ports:
  - name: radius-auth
    port: 1812
    targetPort: 1812
    protocol: UDP
  - name: radius-acct
    port: 1813
    targetPort: 1813
    protocol: UDP
