apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity-system

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap-smb.yaml
  - configmap-init.yaml
  - secret.yaml
  - statefulset.yaml
  - service.yaml
