apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: storage-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: storage-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
  annotations:
    metallb.universe.tf/address-pool: vlan600-management
    metallb.universe.tf/loadBalancerIPs: 192.168.255.70
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.255.70
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: storage-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
  annotations:
    metallb.universe.tf/address-pool: vlan600-management
    metallb.universe.tf/loadBalancerIPs: 192.168.255.71
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.255.71
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
  ports:
  - name: console
    port: 80
    targetPort: 9001
    protocol: TCP
